
CC=/usr/bin/cc

CFLAGS= -I$(IDIR) -std=iso9899:1999 -std=iso9899:1999 -m64 -g -O0 \
	-march=k8 -mtune=k8 -Wl,-rpath=/opt/bw/lib,--enable-new-dtags \
   	-fno-builtin -malign-double -mpc80

CPPFLAGS=-D_TS_ERRNO -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE -D_X_OPEN_SOURCE=600

LIBS = -lm -lgmp

OBJ = rw.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

rw: $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS) $(LIBS)

clean:
	rm -f *.o rw
