
IDIR = .

CC=/opt/bw/gcc9/bin/gcc

CFLAGS= -I$(IDIR) -std=iso9899:1999 -m64 -O0 -g -fno-fast-math -fno-builtin

CPPFLAGS=-D_TS_ERRNO -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
		 -D_X_OPEN_SOURCE=600

LIBS = -lm

DEPS = v.h
SRCS = $(wildcard c*.c)
OBJS = $(SRCS:.c=.o)

%.o: %.c $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

cplex_test: $(OBJS)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS) $(LIBS)

clean:
	rm -f $(OBJS) cplex_test
